# Generated by Django 5.1.4 on 2025-02-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OnionSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, unique=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("hyperlinks", models.JSONField(default=list)),
                ("keyword", models.CharField(blank=True, max_length=100, null=True)),
                ("snapshot_url", models.URLField(blank=True, null=True)),
                ("crawl_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
