# Generated by Django 5.1.4 on 2025-02-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Crawler_frontend", "0002_remove_onionsite_snapshot_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="onionsite",
            name="snapshot",
            field=models.ImageField(blank=True, null=True, upload_to="snapshots/"),
        ),
    ]
